name: Execute e2e tests
description: Installation env and execution e2e tests

runs:
  using: composite
  steps:
    - name: Install packages
      shell: bash
      run: yarn install

    - name: Start selenoid container
      shell: bash
      run: yarn selenoid:start

    - name: Run server
      shell: bash
      run: yarn start:sampleApp &

    - name: Run tests
      shell: bash
      run: yarn test
