name: publish-package
on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  master_tests:
    name: Run e2e tests

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'chore(release)')"

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.WDIO_TOKEN }}
      - name: Use Node.js v14.15.1
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.1

      - name: Install packages
        run: pnpm install

      - name: Run server
        run: pnpm start:sampleApp &

      - name: Run tests
        run: pnpm test

      - uses: sonots/slack-notice-action@v3
        with:
          status: ${{ job.status }}
        env:
          GITHUB_TOKEN: ${{ secrets.WDIO_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_BOT_NOTIFICATION }}
          if: failure()

  release_package:
    needs: master_tests

    name: Release package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.WDIO_TOKEN }}

      - name: Install packages
        run: pnpm install

      - name: run standart version
        run: |
          git config user.name ${{ secrets.USERNAME }}
          git config user.email "${{ secrets.MAIL }}"
          pnpm release

      - name: push changes
        run: git push --follow-tags origin master

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - uses: sonots/slack-notice-action@v3
        with:
          status: ${{ job.status }}
          text_on_success: 'New version wdio-allure-ts published successfully'
          text_on_fail: 'Publish failed, please check'
        env:
          GITHUB_TOKEN: ${{ secrets.WDIO_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_BOT_NOTIFICATION }}
        if: always()
