name: NOTIFY CHANGES

on:
  push:
    branches:
      - master

jobs:
  slack_notification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: 'wdio-allure-ts-ci'
          SLACK_USERNAME: 'Git CI boot'
          SLACK_WEBHOOK: ${{ secrets.SLACK_BOT_NOTIFICATION }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: New changes PR here
